# Generated by Django 3.0 on 2019-12-18 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categroy',
            new_name='category',
        ),
    ]
